apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hello-whale
    namespace: {{ .Env.KUBE_NAMESPACE }}
    labels:
      app: hello-whale
  spec:
    replicas: 5
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    selector:
      matchLabels:
        app: hello-whale
    template:
      metadata:
        labels:
          app: hello-whale
        annotations:
          "git/commit": {{ .Env.CI_COMMIT_SHA }}
      spec:
        imagePullSecrets:
        - name: regcred
        containers:
        - name: hello-whale
          image: registry-demo.cloud.avalara.io/sre/demo:{{ .Env.CI_COMMIT_SHA }}
          imagePullPolicy: Always
          env:
          - name: ENVIRONMENT_NAME
            value: {{ .Env.ENVIRONMENT_NAME }}
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          ports:
          - containerPort: 80
            name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 1
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http
              httpHeaders:
                - name: Host
                  value: hello-whale.{{ .Env.KUBE_NAMESPACE }}.127.0.0.1.xip.io
            initialDelaySeconds: 1
            periodSeconds: 1

- apiVersion: v1
  kind: Service
  metadata:
    name: hello-whale
    namespace: {{ .Env.KUBE_NAMESPACE }}
  spec:
    ports:
    - port: 80
    selector:
      app: hello-whale
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: hello-whale
    namespace: {{ .Env.KUBE_NAMESPACE }}
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
      - host: hello-whale.{{ .Env.KUBE_NAMESPACE }}.127.0.0.1.xip.io
        http:
          paths:
          - path: /
            backend:
              serviceName: hello-whale
              servicePort: 80

